
services:
  ssc4framesdev: 
    image: mcr.microsoft.com/devcontainers/python:3-trixie
    volumes:
      # note: host paths are relative to the first docker-compose.yml in devcontainer.json 
      - ../:/workspaces/SSC4Frames:cached
      # mount another directory
      # - /some/other/host/data/directory:/workspaces/SSC4Frames/data:cached
    command: sleep infinity

