name: Build Docker Image on Version Change

run-name: ${{ github.actor }} published a new version

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  # Job 1: Build Docker image
  build:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.version_changed.outputs.changed }}
      curr_version: ${{ steps.get_curr_version.outputs.curr_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 2  # Needed to compare with previous commit

      - name: Get previous version
        id: get_prev_version
        run: |
          git show HEAD^:pyproject.toml > old_pyproject.toml
          prev_version=$(grep '^version' old_pyproject.toml | sed 's/version *= *//; s/"//g')
          echo "prev_version=$prev_version" >> $GITHUB_OUTPUT
          rm old_pyproject.toml

      - name: Get current version
        id: get_curr_version
        run: |
          curr_version=$(grep '^version' pyproject.toml | sed 's/version *= *//; s/"//g')
          echo "curr_version=$curr_version" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: version_changed
        run: |
          if [ "${{ steps.get_prev_version.outputs.prev_version }}" != "${{ steps.get_curr_version.outputs.curr_version }}" ]; then
            echo "Version changed."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No version change."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        if: steps.version_changed.outputs.changed == 'true'
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          echo "Building and pushing new docker image for latest version ${{ steps.get_curr_version.outputs.curr_version }}."
          # docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:${{ steps.get_curr_version.outputs.curr_version }} --platform linux/arm64,linux/amd64 --push .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:${{ steps.get_curr_version.outputs.curr_version }} .
          
      - name: Push Docker image
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:${{ steps.get_curr_version.outputs.curr_version }}

      - name: Push Docker image tags
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:${{ steps.get_curr_version.outputs.curr_version }} ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ssc4frames:latest
